vich_uploader:
    db_driver: orm

#    mappings:
#        products:
#            uri_prefix: /assets
#            upload_destination: '%kernel.project_dir%/public/assets'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#

